## Numpy Assignment 1

- Student Name:
- Student RegNo:

### Instructions
- Please answer the exercises to the best of your knowledge.
- The assignment is out of 10 marks and will contribute partially to your final result.

In [198]:
#create numpy one dimentional array with 10 elements
import numpy as num
myArray = num.random.randint(90,100, size=10)
myArray

array([92, 90, 98, 98, 93, 98, 92, 98, 94, 93])

In [185]:
#create an numpy array from a python list
my_list = [95, 90, 93, 93, 97, 99, 93, 95, 92, 94]
#my_array = num.asarray(my_list)
my_array = num.array(my_list)
print (my_array) # printing my_array
type(my_array)

[95 90 93 93 97 99 93 95 92 94]


numpy.ndarray

In [186]:
# create an array of five values evenly spaced between 0 and 1
evenArray=num.arange(0,1,0.2)
evenArray

array([0. , 0.2, 0.4, 0.6, 0.8])

In [187]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
num.random.seed(0)
myStdDev = 3
myMean = 0
num.random.normal(myMean, myStdDev, size=(3, 3))

array([[ 5.29215704,  1.20047163,  2.93621395],
       [ 6.7226796 ,  5.60267397, -2.93183364],
       [ 2.85026525, -0.45407162, -0.30965656]])

In [188]:
#creat a 5x5 array with complex numbers
complexArray = num.random.normal(1,2, size=(5,5)) + num.random.normal(1,2, size=(5,5)) * 1j
complexArray

array([[ 1.821197  +0.3041757j ,  1.28808714+1.31269794j,
         3.90854701+3.46058136j,  2.52207545+3.4047597j ,
         1.24335003+0.22534637j],
       [ 1.88772647+0.3953945j ,  1.66734865-1.09710593j,
         3.98815815-1.84003587j,  0.58968347-2.41254038j,
         1.6261354 +4.90155079j],
       [-0.70819148-0.01930436j, -4.10597963+0.1238514j ,
         2.30723719-1.50559072j,  2.7288724 +2.55498071j,
        -0.48433004-2.2277957j ],
       [ 5.53950925+0.57451944j, -1.90873135-0.79093312j,
         1.09151703+1.773805j  ,  0.6256323 -0.02161028j,
         4.06555843-1.36126437j],
       [ 3.93871754+0.94363554j,  1.30989485+1.85666374j,
         1.75632504+1.13303444j, -0.7755715 +1.6049438j ,
        -2.96159294-0.26864419j]])

In [189]:
#create a one dimentional array with 20 elements and return elements from 3 to 7

In [190]:
#create a 3x3 array of random integers and reverse elements of the first row

In [191]:
#create 2 4x4 arrays and stack them both vertically and horizontally

In [192]:
#what are the rules of numpy broadcasting?

In [193]:
# create two 3X3 matrices that are incopatible and raise an error

In [194]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4