## Numpy Assignment 1

- Student Name:
- Student RegNo:

### Instructions
- Please answer the exercises to the best of your knowledge.
- The assignment is out of 10 marks and will contribute partially to your final result.

In [2]:
#create numpy one dimentional array with 10 elements
import numpy as num
num.random.seed(0)
myArray = num.random.randint(90,100, size=10)
print(myArray)
print(myArray.ndim)

[95 90 93 93 97 99 93 95 92 94]
1


In [3]:
#create an numpy array from a python list
my_list = [95, 90, 93, 93, 97, 99, 93, 95, 92, 94] #creating a list
print(type(my_list))
#my_array = num.asarray(my_list)
my_array = num.array(my_list)
print (my_array) # printing my_array
type(my_array)

<class 'list'>
[95 90 93 93 97 99 93 95 92 94]


numpy.ndarray

In [4]:
# create an array of five values evenly spaced between 0 and 1
#evenArray=num.linspace(0, 1, 5)
evenArray=num.arange(0,1,0.2)
evenArray

array([0. , 0.2, 0.4, 0.6, 0.8])

In [5]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
num.random.seed(0)
myStdDev = 3
myMean = 0
num.random.normal(myMean, myStdDev, size=(3, 3))

array([[ 5.29215704,  1.20047163,  2.93621395],
       [ 6.7226796 ,  5.60267397, -2.93183364],
       [ 2.85026525, -0.45407162, -0.30965656]])

In [6]:
#creat a 5x5 array with complex numbers
complexArray = num.random.normal(1,2, size=(5,5)) + num.random.normal(1,2, size=(5,5)) * 1j
complexArray
complexArray.ndim

2

In [7]:
#create a one dimentional array with 20 elements and return elements from 3 to 7
num.random.seed(0)
twentyElementsArray=num.random.randint(1,100, size=20)
print(twentyElementsArray)
print(twentyElementsArray[3:8])


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[68 68 10 84 22]


In [8]:
#create a 3x3 array of random integers and reverse elements of the first row
num.random.seed(0)
randomIntsArray=num.random.randint(1,100, size=(3,3))
print(randomIntsArray)
reversedArray=num.flip(randomIntsArray[0,:], axis=0)
print(reversedArray)

[[45 48 65]
 [68 68 10]
 [84 22 37]]
[65 48 45]


In [9]:
#create 2 4x4 arrays and stack them both vertically and horizontally
firstArray = num.random.randint(1, 50, size=(4,4))
secondArray = num.random.randint(50,100,size=(4,4))
print(firstArray)
print("")
print(secondArray)
#stacking arrays
verticallyStacked = num.vstack([firstArray, secondArray])
horizontallyStacked = num.hstack([firstArray, secondArray]) 
print(" ")
print(verticallyStacked)
print(" ")
print(horizontallyStacked)


[[24  7 25 25]
 [13  2 39 40]
 [24 47 25 18]
 [38 26 14  9]]

[[59 70 66 55]
 [65 97 50 68]
 [85 74 99 79]
 [69 69 64 89]]
 
[[24  7 25 25]
 [13  2 39 40]
 [24 47 25 18]
 [38 26 14  9]
 [59 70 66 55]
 [65 97 50 68]
 [85 74 99 79]
 [69 69 64 89]]
 
[[24  7 25 25 59 70 66 55]
 [13  2 39 40 65 97 50 68]
 [24 47 25 18 85 74 99 79]
 [38 26 14  9 69 69 64 89]]


In [10]:
#what are the rules of numpy broadcasting?
#Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
#Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
#Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [18]:
# create two 3X3 matrices that are incopatible and raise an error
num.random.seed(0)
#creating a 3x2 array
array1=num.random.randint(1, 10, (3, 2))
print(array1)
print("")
print(array1.shape)
#creating a 2x2 array
array2=num.random.randint(10, 20, (2, 2))
print("")
print(array2)
array2.shape
#Adding array1 + array2 should raise an error because the two arrays do not meet rule 3 of array broadcasting above.
print(array1 + array2)

[[6 1]
 [4 4]
 [8 4]]

(3, 2)

[[15 12]
 [14 17]]


ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [12]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4
num.random.seed(0)
randomArray = num.random.randint(1, 20, (4, 4))
print(randomArray)
randomArray > 4 #Checking for values greater than 4

[[13 16  1  4]
 [ 4  8 10 19]
 [ 5  7 13  2]
 [ 7  8 15 18]]


array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])