## Numpy Assignment 1

- Student Name:Lunkuse Jesca Medrine
- Student RegNo:2021/HDO7/23723U

### Instructions
- Please answer the exercises to the best of your knowledge.
- The assignment is out of 10 marks and will contribute partially to your final result.

In [2]:
#create numpy one dimentional array with 10 elements
import numpy as np 
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#create an numpy array from a python list
int = list(range(5))
np.array(int)

array([0, 1, 2, 3, 4])

In [7]:
# create an array of five values evenly spaced between 0 and 1
values = np.linspace(0, 1, 5)
values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
nd_array = np.random.normal(0, 3, (3, 3))
nd_array

array([[ 1.23179551,  0.43213071,  4.36282052],
       [ 2.28311318,  0.36502505,  1.3315897 ],
       [ 1.00102298,  4.48223722, -0.61547479]])

In [11]:
#creat a 5x5 array with complex numbers
np.complex_((5,5))

array([5.+0.j, 5.+0.j])

In [22]:
#create a one dimentional array with 20 elements and return elements from 3 to 7
a2 = np.arange(20)
a2[3:8]

array([3, 4, 5, 6, 7])

In [4]:
#create a 3x3 array of random integers and reverse elements of the first row
a3 = np.random.randint(1,10, (3,3))
a3[1: ,::-1,]


array([[1, 8, 7],
       [6, 8, 4]])

In [36]:
#create 2 4x4 arrays and stack them both vertically and horizontally
a4 = np.random.randint(1,10,(4,4))
a5 = np.random.randint(5,15,(4,4))
np.vstack([a4, a5])
np.hstack([a4, a5])

array([[ 5,  1,  7,  5, 12,  9,  6,  8],
       [ 3,  5,  7,  4,  8, 14,  7, 10],
       [ 4,  8,  9,  6,  7,  8, 10, 12],
       [ 1,  9,  6,  5,  7, 12,  6, 11]])

In [ ]:
#what are the rules of numpy broadcasting?
#Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is *padded* with ones on its leading (left) side.
#Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
#Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [ ]:
# create two 3X3 matrices that are incopatible and raise an error

In [38]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4
a6 = np.random.randint(2,8, (4,4))
a6[a6 > 4]

array([7, 5, 6, 6])