## Numpy Assignment 1

- Student Name: FRANK KATO
- Student RegNo: 2021/HDO7/3232U

### Instructions
- Please answer the exercises to the best of your knowledge.
- The assignment is out of 10 marks and will contribute partially to your final result.

In [17]:
#create numpy one dimentional array with 10 elements
import numpy as np
nump_array = np.arange(0, 20, 2) #numpy one dimensional array with 10
nump_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
#create an numpy array from a python list
L = np.array([1,2,3,5,6,7]) #numpy array
L      

array([1, 2, 3, 5, 6, 7])

In [19]:
# create an array of five values evenly spaced between 0 and 1
L3 = np.linspace(0,1,5) #array of five values evenly spaced between 0 and 1
L3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 3
L4 = np.random.normal(0, 1, (3, 3)) #a 3x3 array of normally distributed values
L4

array([[ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323]])

In [21]:
#creat a 5x5 array with complex numbers
complex_array = np.ones((5,5), dtype=complex) #a 5x5 array with complex numbers
complex_array

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [22]:
#create a one dimentional array with 20 elements and return elements from 3 to 7
L5 = np.arange(20) 
L5[3:7] #return elements from 3 to 7


array([3, 4, 5, 6])

In [23]:
#create a 3x3 array of random integers and reverse elements of the first row
np.random.seed(0)  # seed for reproducibility
L6 = np.random.randint(10, size=(3,3)) #3X3 array of random integers
L6[0, ::-1] #reverse elements of first row

array([3, 0, 5])

In [33]:
#create 2 4x4 arrays and stack them both vertically and horizontally
array1 = np.arange(16).reshape(4,4) #4x4 array of 16 elements
array2 = np.ones(16, dtype=int).reshape(4,4)#4x4 array with 16 ones
print(array1,array2)
np.hstack((array1,array2)) # 2 4x4 arrays stacked horizontally
np.vstack((array1,array2)) # 2 4x4 arrays stacked vertically

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1]])

    #what are the rules of numpy broadcasting?
    1. If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension. This makes two arrays have equal dimensions
    2. Also,Make each dimension of the two arrays the same size.
    3. An error is raised if in any dimension sizes disagree and none is equal to zero

In [ ]:
# create two 3X3 matrices that are incompatible and raise an error


In [ ]:
#create a 4x4 matrix with random integers and use a boolean mask to check for those above 4